openapi: 3.0.3
info:
  title: Easyapp API
  version: 1.0.0
  description: API documentation for easyapp
paths:
  /api/hello/:
    get:
      operationId: api_hello_retrieve
      description: Get a hello world message
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'
          description: ''
  /api/auth/register/:
    post:
      operationId: auth_register_create
      description: Register a new member and return token
      tags:
      - auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
      responses:
        '201':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthTokenResponse'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /api/auth/login/:
    post:
      operationId: auth_login_create
      description: Log in an existing member and return token
      tags:
      - auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthTokenResponse'
        '400':
          description: Invalid credentials
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /api/auth/me/:
    get:
      operationId: auth_me_retrieve
      description: Get current authenticated member
      tags:
      - auth
      security:
      - tokenAuth: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Member'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /api/auth/logout/:
    post:
      operationId: auth_logout_create
      description: Logout current authenticated member
      tags:
      - auth
      security:
      - tokenAuth: []
      responses:
        '204':
          description: ''
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    Message:
      type: object
      properties:
        message:
          type: string
          maxLength: 200
        timestamp:
          type: string
          format: date-time
          readOnly: true
      required:
      - message
      - timestamp
    Member:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        nickname:
          type: string
          maxLength: 50
        created_at:
          type: string
          format: date-time
          readOnly: true
      required:
      - id
      - nickname
      - created_at
    AuthTokenResponse:
      type: object
      properties:
        token:
          type: string
        member:
          $ref: '#/components/schemas/Member'
      required:
      - token
      - member
    RegisterRequest:
      type: object
      properties:
        nickname:
          type: string
        password:
          type: string
      required:
      - nickname
      - password
    LoginRequest:
      type: object
      properties:
        nickname:
          type: string
        password:
          type: string
      required:
      - nickname
      - password
    ErrorResponse:
      type: object
      properties:
        detail:
          type: string
      required:
      - detail
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
    tokenAuth:
      type: apiKey
      in: header
      name: Authorization
      description: Token-based authentication with required prefix "Token"
