openapi: 3.0.3
info:
  title: Easyapp API
  version: 1.0.0
  description: API documentation for easyapp
paths:
  /api/hello/:
    get:
      operationId: api_hello_retrieve
      description: Get a hello world message
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HelloMessage'
          description: ''
  /api/auth/register/:
    post:
      operationId: auth_register_create
      description: Register a new member and return token
      tags:
      - auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
      responses:
        '201':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthTokenResponse'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /api/auth/login/:
    post:
      operationId: auth_login_create
      description: Log in an existing member and return token
      tags:
      - auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthTokenResponse'
        '400':
          description: Invalid credentials
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /api/auth/me/:
    get:
      operationId: auth_me_retrieve
      description: Get current authenticated member
      tags:
      - auth
      security:
      - tokenAuth: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Member'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /api/auth/logout/:
    post:
      operationId: auth_logout_create
      description: Logout current authenticated member
      tags:
      - auth
      security:
      - tokenAuth: []
      responses:
        '204':
          description: ''
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /api/chat/messages/:
    get:
      operationId: chat_messages_list
      description: List messages from the global chat room
      tags:
      - chat
      security:
      - tokenAuth: []
      parameters:
      - in: query
        name: limit
        required: false
        description: Maximum number of messages to return
        schema:
          type: integer
      - in: query
        name: after_id
        required: false
        description: Return messages with id greater than this value
        schema:
          type: integer
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Message'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    post:
      operationId: chat_messages_create
      description: Create a new message in the global chat room
      tags:
      - chat
      security:
      - tokenAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MessageCreate'
      responses:
        '201':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    HelloMessage:
      type: object
      properties:
        message:
          type: string
          maxLength: 200
        timestamp:
          type: string
          format: date-time
          readOnly: true
      required:
      - message
      - timestamp
    Member:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        nickname:
          type: string
          maxLength: 50
        created_at:
          type: string
          format: date-time
          readOnly: true
      required:
      - id
      - nickname
      - created_at
    AuthTokenResponse:
      type: object
      properties:
        token:
          type: string
        member:
          $ref: '#/components/schemas/Member'
      required:
      - token
      - member
    RegisterRequest:
      type: object
      properties:
        nickname:
          type: string
        password:
          type: string
      required:
      - nickname
      - password
    LoginRequest:
      type: object
      properties:
        nickname:
          type: string
        password:
          type: string
      required:
      - nickname
      - password
    ErrorResponse:
      type: object
      properties:
        detail:
          type: string
      required:
      - detail
    ChatRoom:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 100
      required:
      - id
      - name
    ChatAuthor:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        nickname:
          type: string
          maxLength: 50
      required:
      - id
      - nickname
    Message:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        text:
          type: string
        created_at:
          type: string
          format: date-time
          readOnly: true
        author:
          $ref: '#/components/schemas/ChatAuthor'
        room_id:
          type: integer
      required:
      - id
      - text
      - created_at
      - author
      - room_id
    MessageCreate:
      type: object
      properties:
        text:
          type: string
      required:
      - text
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
    tokenAuth:
      type: apiKey
      in: header
      name: Authorization
      description: Token-based authentication with required prefix "Token"
